name: Build and Publish to GitHub Packages

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: https://npm.pkg.github.com/
          cache: 'yarn'
      - name: Inform me
        run: yarn -v

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build

      - name: Publish to GitHub Packages
        run: yarn publish --access restricted
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NODE_AUTH_TOKEN }}
